image: maven:3-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  
cache:
  paths:
    - .m2/repository/ 
  
stages:
  - test
  - deploy

test:
  stage: test
  cache:
    key: m2
    paths:
      - .m2/repository
  script: 
    - mvn test

# https://docs.gitlab.com/ee/ci/examples/deployment/
deploy_heroku:
  stage: deploy  
  script: 
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_API_KEY
  when: manual  
  only:
    - master
